
package ui.frm;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author arace
 */
public class FrmWelcome extends javax.swing.JFrame {

    /**
     * Creates new form FrmWelcome
     */
    public FrmWelcome() {
        initComponents();
       
      
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJoinGame = new javax.swing.JButton();
        btnCreateGame = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timbiriche");
        setAlwaysOnTop(true);
        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(720, 576));
        setMinimumSize(new java.awt.Dimension(720, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJoinGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/btnJoinGame.png"))); // NOI18N
        btnJoinGame.setBorderPainted(false);
        btnJoinGame.setContentAreaFilled(false);
        btnJoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnJoinGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 210, 210));

        btnCreateGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/btnCreateGame.png"))); // NOI18N
        btnCreateGame.setBorderPainted(false);
        btnCreateGame.setContentAreaFilled(false);
        btnCreateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, 210));

        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, 70));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinGameActionPerformed
        Icon icon = new ImageIcon(new ImageIcon(getClass().getResource("/sources/btnCreateGame.png")).getImage());
//        System.getProperty("user.dir")+("\\src\\main\\java\\sources\\btnCreateGame.png"
        btnJoinGame.setIcon(icon);
        FrmJoinGame v = new FrmJoinGame();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJoinGameActionPerformed

    private void btnCreateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGameActionPerformed
        Icon icon1 = new ImageIcon(new ImageIcon(getClass().getResource("/sources/btnJoinGame.png")).getImage());
        btnCreateGame.setIcon(icon1);
        FrmCreateGame v = new FrmCreateGame();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateGameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGame;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoinGame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    

    

}
